dataset:
  root_dir: "data/raw/UCF-101"
  train_split: "data/splits/trainlist01.txt"
  test_split: "data/splits/testlist01.txt"
  class_file: "data/splits/classInd.txt"

preprocessing:
  num_frames: 16
  image_size: 112

training:
  batch_size: 4
  epochs: 20
  learning_rate: 0.0001

model:
  name: "r3d_18"
  num_classes: 101

device:
  use_cuda: true